@startuml component_diagram
skinparam componentStyle rectangle

database "Data Source" as DB1 
[IDS Connector] as C1
[IDS Connector] as C2
database "Data Sink" as DB2


[Clearing House] as CH

component "App Store" as AS {
  [App] as AP
}

note as N1
  This could be 
  the sanitizer app
end note

N1 ..> AP

[Metadata Broker] as MB
[Vocabulary Hub] as VH

DB1 -right-> C1
C1 -right-> C2: data
C2 -right-> DB2

C1 .down.> CH: metadata
C2 ..> CH: metadata

C1 .up.> MB: metadata
C2 ..> MB: metadata

C2 <..> VH: metadata
C1 <.. AS: app
@enduml