@startuml connector
' skinparam componentStyle rectangle

component "IDS Connector" as C {
    [Connector Core] as Core
    component "Usage Control\n<<MYDATA>>" as UC {
        [PMP]
        [PDP]
        [PEP]
        PMP -> PDP: Deploy
        PDP <-> PEP: Decision
    }
    () "Policy" as PMP_INT
    [Sanitization App] as SAP


    UC <--> SAP: Data
    PMP_INT -up-> PMP
    Core <-down-> UC: Data
}

@enduml